---
# template for mirko's lab
obj_ontap_svm:
    ipspace:
      name:                   "Default"
    language:                 "c.UTF-8"
    comment: ""
    dns:
      domains:
        -                     "slash.local"
      servers:
        -                     "172.16.0.32"
    routes:
      - gateway:              "172.16.0.1"
        destination:
          netmask:            "32"
          address:            "0.0.0.0"
    snapshot_policy:
      name:                  "none"
