---
##############################################################
### Run Pre-steps
##############################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must pass the 'ontap_ip_interface_name' and 'ontap_svm_name'"
      - "or the '__ontap_ip_interface_input__' variable"
  when:
    - ((ontap_ip_interface_name is undefined or
      ontap_svm_name is undefined) and
      __ontap_ip_interface_input__ is undefined)
  tags:
    - always

- name: Validate Action
  fail:
    msg:
      - "You must pass the 'ontap_ansiblerole_action' variable"
  when:
    - ontap_ansiblerole_action is undefined
  tags:
    - always

- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true
  tags:
    - always

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        ontap_svm_object: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == ontap_svm_name
    - name: Find IP Interface
      ansible.builtin.set_fact:
        ontap_ip_interface_object: "{{ ip_interface_item }}"
      loop:
        "{{ ontap_svm_object.ip_interfaces | list }}"
      loop_control:
        label:    "{{ ip_interface_item.name }}"
        loop_var: ip_interface_item
      when:
        - ip_interface_item.name == ontap_ip_interface_name
  when:
    - source_inventory is defined
    - source_inventory == true
# FIXME - Additioanl condition required to check, if SVM has been found in inventory

- name: Source Template Information
  block:
    - name: Merge Defaults/Vars with Input
      ansible.builtin.set_fact:
        ontap_ip_interface_object: "{{ ontap_ip_interface_object | combine(__ontap_ip_interface_input__, recursive=True) }}"
  when:
    - __ontap_ip_interface_input__ is defined



##############################################################
### Initiate Action
##############################################################

- name: Read LIF Information into 'ontap_ip_interface_object'
  include_tasks:      ontap_ip_interface_info.yml
  vars:
    ontap_login:
      <<: *ontap_login
  when:
    - ontap_ansiblerole_action == "info"

- name: Create LIF
  include_tasks:      ontap_ip_interface_create.yml
  vars:
    ontap_login:
      <<: *ontap_login
  when:
    - ontap_ansiblerole_action == "create"

- name: Delete LIF
  include_tasks:      ontap_ip_interface_delete.yml
  vars:
    ontap_login:
      <<: *ontap_login
  when:
    - ontap_ansiblerole_action == "delete"