---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Create IP Interface
  na_ontap_interface:
    state:                        present
    interface_name:               "{{ ontap_ip_interface_object.name }}"
    vserver:                      "{{ ontap_ip_interface_object.svm.name }}"
    address:                      "{{ ontap_ip_interface_object.ip.address              | default(omit) }}"
    netmask:                      "{{ ontap_ip_interface_object.ip.netmask              | default(omit) }}"
    service_policy:               "{{ ontap_ip_interface_object.service_policy.name     | default(omit) }}"
    home_node:                    "{{ ontap_ip_interface_object.location.home_node.name | default(omit) }}"
    home_port:                    "{{ ontap_ip_interface_object.location.home_port.name | default(omit) }}"
# FIXME - This one is ugly, but "role" must be provided as long as we have to use ZAPI here
    role:                         "data"
    <<: *ontap_login