---
################################################################################
# Description:
# -----------
# - Reading a single SVM 
# - Taking 'ontap_svm_input' with additional optional parameters
################################################################################
- hosts:                          "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:     "info"

  tasks:
  - name: Create SVM
    include_role:
      name:                       ../roles/ontap_svm
    vars:
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
      __ontap_source_inventory__: "{{ source_inventory | default(false) }}"
      __ontap_svm_input__:        "{{ ontap_svm_input }}"
