---
################################################################################
# Description:
# -----------
# - Creating a single IP interface (LIF) 
# - Taking 'ontap_ip_interface_input' with additional optional parameters
#   or sourcing IP interface state from the inventory by taking 
#   ontap_ip_interface_input.name and 'source_inventory=true'
################################################################################
- hosts:                          "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:     "create"

  tasks:
  - name: Create IP Interface
    include_role:
      name:                       ../roles/ontap_ip_interface
    vars:
      __ontap_ansiblerole_action__:
                                    "{{ ontap_ansiblerole_action }}"
      __ontap_source_inventory__:   "{{ source_inventory | default(false) }}"
      __ontap_ip_interface_input__: "{{ ontap_ip_interface_input }}"