---
################################################################################
# Description:
# -----------
# - Creating a single qtree 
# - Taking 'ontap_qtree_input' with additional optional parameters
#   or sourcing qtree state from the inventory by taking 
#   ontap_qtree_input.name and 'source_inventory=true'
################################################################################
- hosts:                          "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:     "create"

  tasks:
  - name: Create Qtree
    include_role:
      name:                       ../roles/ontap_qtree
    vars:
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
      __ontap_source_inventory__: "{{ source_inventory | default(false) }}"
      __ontap_qtree_input__:      "{{ ontap_qtree_input }}"