---
################################################################################
# Description:
# -----------
# - Creating a single qtree 
# - Taking 'ontap_quota_input' with additional optional parameters
#   or sourcing quota state from the inventory by taking 
#   ontap_quota_input.type and 'source_inventory=true'
################################################################################
- hosts:                          "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:     "create"
  
  tasks:
  - name: Create Quota Rule
    include_role:
      name:                       ../roles/ontap_quota_rule
    vars:
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
      __ontap_source_inventory__: "{{ source_inventory | default(false) }}"
      __ontap_quota_input__:      "{{ ontap_quota_input }}"