---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  vars:
    username: "admin"
    password: "Netapp12"
    aggr: "aggr1"
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ volume_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: "{{ size_mb }}"
      size_unit: "mb"
      policy: "default"
      junction_path: "/{{ volume_name }}"
      hostname: "{{ cluster }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
