---
# tasks file for ontap_quota_rule
################################################################################
#
# Variables accepted by this role:
# -------------------------------
#
# Mandatory:
# __ontap_ansiblerole_action__:        create, delete, info
# __ontap_quota_rule_input__:          Input object with additional optional
#                                      parameters to action on
#                                      (according to SVM data model)
#                    Mandatory childs: .type        - Quota type
#                                      .volume.name - Associated volume
#                                      .svm.name    - Owning SVM
#
# Optional:
# __ontap_source_inventory__:          Source object input from Ansible
#                                      inventory and host/group vars
# 
################################################################################



################################################################################
### Run role input validation
################################################################################

- name: Validate Mandatory Input
  fail:
    msg:
# FIXME: Elegant solution required for checking input depending on quota type...
      - "You must provide '__ontap_quota_rule_input__' including child(s):
        .type, .volume.name, .svm.name"
      - "and '__ontap_ansiblerole_action__'"
      - "> __ontap_quota_rule_input__.svm.name:    {{ __ontap_quota_input__.svm.name | default ('') }}"
      - "> __ontap_quota_rule_input__.volume.name: {{ __ontap_quota_input__.volume.name | default ('') }}"
      - "> __ontap_quota_rule_input__.type:        {{ __ontap_quota_input__.type | default ('') }}"
      - "> __ontap_ansiblerole_action__:           {{ __ontap_ansiblerole_action__ | default ('') }}"
  when:
    - (__ontap_quota_rule_input__.svm.name     | default('') == "" or
       __ontap_quota_rule_input__.volume.name  | default('') == "" or
       __ontap_quota_rule_input__.type         | default('') ==""
       )
    - (__ontap_ansiblerole_action__ | default('')) not in ["create", "delete", "info"]
        ))
  tags:
    - always



################################################################################
### Source input parameters into object
################################################################################

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        __ontap_svm_object__: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == __ontap_quota_rule_input__.svm.name
# FIXME - Policy is always "default". ONTAP REST currently does not allow managing custom quota policies
    - name: Find Quota Policy
      ansible.builtin.set_fact:
        __ontap_quota_policy_object__: "{{ quota_policy_item }}"
      loop:
        "{{ __ontap_svm_object__.quota_policies | list }}"
      loop_control:
        label:    "{{ quota_policy_item.name }}"
        loop_var: quota_policy_item
      when:
        - quota_policy_item.name == "default"
# FIXME - Not sure how to fix... There is simply no descriptive identifier, that you can set (ID or Name)
    - name: Find Quota Rule
      ansible.builtin.set_fact:
        __ontap_quota_rule_object__: "{{ quota_rule_item }}"
      loop:
        "{{ ontap_quota_policy_object.quota_rules | list }}"
      loop_control:
        label:    "{{ quota_rule_item }}"
        loop_var: quota_rule_item
      when:
        - quota_rule_item.volume.name         == __ontap_quota_rule_input__.volume.nae
        - quota_rule_item.type                == __ontap_quota_rule_input__.type
        - quota_rule_item.qtree | default('') == __ontap_quota_rule_input__.qtree | default('')
        - quota_rule_item.users | default('') == __ontap_quota_rule_input__.users | default('')
        - quota_rule_item.group | default('') == __ontap_quota_rule_input__.group | default('')
  when:
    - __source_inventory__ is defined
    - __source_inventory__

- name: Source Template Information
  block:
    - name: Merge Defaults/Vars with Input
      ansible.builtin.set_fact:
        __ontap_quota_rule_object__: "{{ __ontap_quota_rule_object__ | default({}) | combine(__ontap_quota_rule_input__, recursive=True) }}"

- name: Verify Data Sourcing
  fail:
    msg:
      - "Mandatory data could not be sourced:"
      - "> __ontap_quota_rule_object__.svm.name    --> {{ __ontap_quota_rule_object__.svm.name }}"
      - "> __ontap_quota_rule_object__.volume.name --> {{ __ontap_quota_rule_object__.volume.name }}"
      - "> __ontap_quota_rule_object__.type        --> {{ __ontap_quota_rule_object__.type }}"
  when:
    - __ontap_quota_rule_object__.svm.name    | default('') == "" or
      __ontap_quota_rule_object__.volume.name | default('') == "" or
      __ontap_quota_rule_object__.type        | default('') == ""
  tags:
    - always



################################################################################
### Initiate role action
################################################################################

- name: Read Quota Information into 'ontap_quota_rule_object'
  include_tasks:      ontap_quota_rule_info.yml
  when:
    - __ontap_ansiblerole_action__ == "info"

- name: Create Quota Rule
  include_tasks:      ontap_quota_rule_create.yml
  when:
    - __ontap_ansiblerole_action__ == "create"

- name: Delete Quota Rule
  include_tasks:      ontap_quota_rule_delete.yml
  when:
    - __ontap_ansiblerole_action__ == "delete"