---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Delete Tree Quota
  na_ontap_quotas:
    state:                        present
    vserver:                      "{{ __ontap_quota_rule_object__.svm.name }}"
    type:                         "{{ __ontap_quota_rule_object__.type }}"
    volume:                       "{{ __ontap_quota_rule_object__.volume.name }}"
    quota_target:                 "{{ __ontap_quota_rule_object__.qtree.name }}"
# FIXME - Policy is always "default". ONTAP REST currently does not allow managing custom quota policies
    policy:                       default
    activate_quota_on_change:     resize
    <<: *ontap_login
  when:
    - __ontap_quota_rule_object__.type == "tree"
- name: Delete User Quota
    state:                        present
    vserver:                      "{{ __ontap_quota_rule_object__.svm.name }}"
    type:                         "{{ __ontap_quota_rule_object__.type }}"
    volume:                       "{{ __ontap_quota_rule_object__.volume.name }}"
# FIXME - Not evaluated with users
    quota_target:                 "{{ __ontap_quota_rule_object__.users.name }}"
# FIXME - Policy is always "default". ONTAP REST currently does not allow managing custom quota policies
    policy:                       default
    activate_quota_on_change:     resize
    <<: *ontap_login
  when:
    - __ontap_quota_rule_object__.type == "user"
- name: Delete Group Quota
    state:                        present
    vserver:                      "{{ __ontap_quota_rule_object__.svm.name }}"
    type:                         "{{ __ontap_quota_rule_object__.type }}"
    volume:                       "{{ __ontap_quota_rule_object__.volume.name }}"
    quota_target:                 "{{ __ontap_quota_rule_object__.group.name }}"
# FIXME - Policy is always "default". ONTAP REST currently does not allow managing custom quota policies
    policy:                       default
    activate_quota_on_change:     resize
    <<: *ontap_login
  when:
    - __ontap_quota_rule_object__.type == "group"