---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Get LIF Info
  na_ontap_rest_info:
    gather_subset:
      - storage/quota/rules
    parameters:
      volume.name:                "{{ __ontap_quota_rule_object__.volume.name }}"
      type:                       "{{ __ontap_quota_rule_object__.type }}"
      qtree.name:                 "{{ __ontap_quota_rule_object__.qtree.name | default(omit) }}"
      users.name:                 "{{ __ontap_quota_rule_object__.users.name | default(omit) }}"
      group.name:                 "{{ __ontap_quota_rule_object__.group.name | default(omit) }}"
    fields:
# FIXME - List of required fields has to be added for to improve overall efficiency
      - '**'
    <<: *ontap_login
  register: __ontap_quota_rule_return__

- name: Set __ontap_quota_rule_return_clean__
  ansible.builtin.set_fact:
    __ontap_quota_rule_return_clean__: "{{ __ontap_quota_rule_return__.ontap_info['storage/quota/rules'].records[0] }}"
  when:
  - __ontap_quota_rule_return__.ontap_info['storage/quota/rules'].num_records == 1

- name: Debug __ontap_quota_rule_return_clean__
  ansible.builtin.debug:
    msg: "{{ __ontap_quota_rule_return_clean__ }}"