---
# tasks file for ontap_qtree
################################################################################
#
# Variables accepted by this role:
# -------------------------------
#
# Mandatory:
# __ontap_ansiblerole_action__:        create, delete, info
# __ontap_qtree_input__:               Input object with additional optional
#                                      parameters to action on
#                                      (according to SVM data model)
#                    Mandatory childs: .name        - Qtree name
#                                      .volume.name - Owning volume
#                                      .svm.name    - Owning SVM
#
# Optional:
# __ontap_source_inventory__:          Source object input from Ansible
#                                      inventory and host/group vars
# 
################################################################################



################################################################################
### Run role input validation
################################################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must provide '__ontap_qtree_input__' including child(s):
        .name, .volume.name, .svm.name"
      - "and '__ontap_ansiblerole_action__'"
      - "> __ontap_qtree_input__.svm.name:    {{ __ontap_qtree_input__.svm.name | default ('') }}"
      - "> __ontap_qtree_input__.volume.name: {{ __ontap_qtree_input__.volume.name | default ('') }}"
      - "> __ontap_qtree_input__.name:        {{ __ontap_qtree_input__.name | default ('') }}"
      - "> __ontap_ansiblerole_action__:      {{ __ontap_ansiblerole_action__ | default ('') }}"
  when:
    - (__ontap_qtree_input__.svm.name    | default('') == "" or
       __ontap_qtree_input__.volume.name | default('') == "" or
       __ontap_qtree_input__.name        | default('') == ""
       )
    - (__ontap_ansiblerole_action__ | default('')) not in ["create", "delete", "info"]
  tags:
    - always



################################################################################
### Source input parameters into object
################################################################################

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        __ontap_svm_object__: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == __ontap_qtree_input__.svm.name
    - name: Find Volume
      ansible.builtin.set_fact:
        __ontap_volume_object__: "{{ volume_item }}"
      loop:
        "{{ __ontap_svm_object__.volumes | list }}"
      loop_control:
        label:    "{{ volume_item.name }}"
        loop_var: volume_item
      when:
        - volume_item.name == __ontap_qtree_input__.volume.name
    - name: Find Qtree
      ansible.builtin.set_fact:
        __ontap_qtree_object__: "{{ qtree_item }}"
      loop:
        "{{ __ontap_volume_object__.qtrees | list }}"
      loop_control:
        label:    "{{ qtree_item.name }}"
        loop_var: qtree_item
      when:
        - qtree_item.name == __ontap_qtree_input__.name
  when:
    - __ontap_source_inventory__ is defined
    - __ontap_source_inventory__ | bool

- name: Merge Defaults/Vars with Input
  ansible.builtin.set_fact:
    __ontap_qtree_object__: "{{ __ontap_qtree_object__ | default({}) | combine(__ontap_qtree_input__, recursive=True) }}"

- name: Verify Data Sourcing
  fail:
    msg:
      - "Mandatory data could not be sourced:"
      - "> __ontap_qtree_object__.svm.name    --> {{ __ontap_qtree_object__.svm.name }}"
      - "> __ontap_qtree_object__.volume.name --> {{ __ontap_qtree_object__.volume.name }}"
      - "> __ontap_qtree_object__.name        --> {{ __ontap_qtree_object__.name }}"
  when:
    - __ontap_qtree_object__.svm.name    | default('') == "" or
      __ontap_qtree_object__.volume.name | default('') == "" or
      __ontap_qtree_object__.name        | default('') == ""
  tags:
    - always



################################################################################
### Initiate role action
################################################################################

- name: Read Qtree Information into 'ontap_qtree_object'
  include_tasks:      ontap_qtree_info.yml
  when:
    - __ontap_ansiblerole_action__ == "info"

- name: Create Qtree
  include_tasks:      ontap_qtree_create.yml
  when:
    - __ontap_ansiblerole_action__ == "create"

- name: Delete Qtree
  include_tasks:      ontap_qtree_delete.yml
  when:
    - __ontap_ansiblerole_action__ == "delete"