---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Get Qtree Info
  na_ontap_rest_info:
    gather_subset:
      - storage/qtree
    parameters:
      svm.name:                   "{{ __ontap_qtree_object__.svm.name }}"
      volume.name:                "{{ __ontap_qtree_object__.volume.name }}"
      name:                       "{{ __ontap_qtree_object__.name }}"
    fields:
# FIXME - List of required fields has to be added for to improve overall efficiency
      - '**'
    <<: *ontap_login
  register: __ontap_qtree_return__

- name: Set __ontap_qtree_return_clean__
  ansible.builtin.set_fact:
    __ontap_qtree_return_clean__: "{{ __ontap_qtree_return__.ontap_info['storage/qtrees'].records[0] }}"
  when:
  - __ontap_qtree_return__.ontap_info['storage/qtrees'].num_records == 1

- name: Debug __ontap_qtree_return_clean__
  ansible.builtin.debug:
    msg: "{{ __ontap_qtree_return_clean__ }}"