#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        sl10599_init_awx.yml
# Author:       Adrian Bronder
# Date:         2020-10-13
# Description:  Configure AWX on rhel1
#
# Collections:  awx.awx
#
# URL:          https://galaxy.ansible.com/awx/awx
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_svm
#
################################################################################

- hosts:              localhost
  gather_facts:       false
  vars:
    input: &input
      tower_host:     "http://ansible.demo.netapp.com"
      tower_username: "admin"
      tower_password: "Netapp1!"
      validate_certs: "no"
  collections:
    - awx.awx

  tasks:
  - name: Disable Auto Download of Role Requirements
    tower_settings:
      settings:
        AWX_ROLES_ENABLED:       false
      <<: *input

  - name: Create Organization in AWX
    tower_organization:
      state:                     present
      name:                      "NetApp LoD"
      <<: *input

  - name: Create Project in AWX
    tower_project:
      state:                     present
      name:                      "LoD Demo - Ansible Pilot"
      description:               "Git repository with ready to use Ansible demos"
      organization:              "NetApp LoD"
      scm_type:                  "git"
      scm_url:                   "https://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@github.com/CXO-Automation/awx_mirko_test"
      scm_branch:                "badrian_dev"
      scm_update_on_launch:      True
      scm_update_cache_timeout:  60
      <<: *input

  - name: Create Custom Credential Type for ONTAP
    tower_credential_type:
      state:                     present
      name:                      "ONTAP Cluster"
      description:               "Default credential type for connecting to ONTAP clusters"
      kind:                      "cloud"
      inputs:
        fields:
          - id:                  "ontap_username"
            type:                "string"
            label:               "Username"
          - id:                  "ontap_password"
            type:                "string"
            label:               "Password"
            secret:              True
      injectors:
        extra_vars:
          ontap_username:        "{{ '{{ ontap_username }}' }}"
          ontap_password:        "{{ '{{ ontap_password }}' }}"
      <<: *input

  - name: Create ONTAP default credential
    tower_credential:
      state:                     present
      name:                      "ONTAP Default Credentials"
      credential_type:           "ONTAP Cluster"
      organization:              "NetApp LoD"
      inputs:
        ontap_username:          "admin"
        ontap_password:          "Netapp1!"
      <<: *input

  - name: Add LoD Inventory
    tower_inventory:
      state:                     present
      name:                      "LoD Inventory"
      description:               "Inventory for virtual lab environment"
      organization:              "NetApp LoD"
      <<: *input

  - name: Add LoD Inventory Source - From Project Root
    tower_inventory_source:
      state:                     present
      name:                      "Project Root Inventory"
      description:               "Inventory file sourced from root of pilot folder"
      inventory:                 "LoD Inventory"
      source:                    "scm"
      source_project:            "LoD Demo - Ansible Pilot"
      source_path:               "ansible_pilot/inventory"
      update_on_project_update:  True
      update_on_launch:          False
      overwrite:                 True
      <<: *input

  - name: Create Job Template for Creating an SVM
    tower_job_template:
      state:                     present
      name:                      "Basic SVM Create"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/pilot_play_basic_create.yml"
      credential:                "ONTAP Default Credentials"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Basic SVM Create'"
        description:             ""
        spec:
        - question_name:         "Action"
          description:           "Describing the action to be performed"
          required:              True
          type:                  "multiplechoice"
          choices:               "create\ndelete"
          variable:              "ontap_ansiblerole_action"
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Management Interface Name"
          description:           "LIF to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_ip_interface_name"
        - question_name:         "Volume Name"
          description:           "Volume to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_volume_name"
      <<: *input

  - name: Create Job Template for Deleting an SVM
    tower_job_template:
      state:                     present
      name:                      "Basic SVM Delete"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/pilot_play_basic_delete.yml"
      credential:                "ONTAP Default Credentials"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Basic SVM Delete'"
        description:             ""
        spec:
        - question_name:         "Action"
          description:           "Describing the action to be performed"
          required:              True
          type:                  "multiplechoice"
          choices:               "create\ndelete"
          variable:              "ontap_ansiblerole_action"
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Volume Name"
          description:           "Volume to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_volume_name"
      <<: *input