#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        sl10599_init_awx.yml
# Author:       Adrian Bronder
# Date:         2020-10-13
# Description:  Configure AWX on rhel1
#
# Collections:  awx.awx
#
# URL:          https://galaxy.ansible.com/awx/awx
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_svm
#
################################################################################

- hosts:              localhost
  gather_facts:       false
  vars:
    input: &input
      tower_host:     "http://ansible.demo.netapp.com"
      tower_username: "admin"
      tower_password: "Netapp1!"
      validate_certs: "no"
  collections:
    - awx.awx

  tasks:
  - name: Disable Auto Download of Role Requirements
    tower_settings:
      settings:
        AWX_ROLES_ENABLED:       false
      <<: *input

  - name: Create Organization in AWX
    tower_organization:
      state:                     present
      name:                      "NetApp LoD"
      <<: *input

  - name: Create Project in AWX
    tower_project:
      state:                     present
      name:                      "LoD Demo - Ansible Pilot"
      description:               "Git repository with ready to use Ansible demos"
      organization:              "NetApp LoD"
      scm_type:                  "git"
      scm_url:                   "https://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@github.com/CXO-Automation/awx_mirko_test"
      scm_branch:                "badrian_dev"
      scm_update_on_launch:      True
      scm_update_cache_timeout:  60
      <<: *input

  - name: Create Custom Credential Type for ONTAP
    tower_credential_type:
      state:                     present
      name:                      "ONTAP Cluster"
      description:               "Default credential type for connecting to ONTAP clusters"
      kind:                      "cloud"
      inputs:
        fields:
          - id:                  "ontap_username"
            type:                "string"
            label:               "Username"
          - id:                  "ontap_password"
            type:                "string"
            label:               "Password"
            secret:              True
      injectors:
        extra_vars:
          ontap_username:        "{{ '{{ ontap_username }}' }}"
          ontap_password:        "{{ '{{ ontap_password }}' }}"
      <<: *input

  - name: Create ONTAP default credential
    tower_credential:
      state:                     present
      name:                      "ONTAP Default Credentials"
      credential_type:           "ONTAP Cluster"
      organization:              "NetApp LoD"
      inputs:
        ontap_username:          "admin"
        ontap_password:          "Netapp1!"
      <<: *input

  - name: Add LoD Inventory
    tower_inventory:
      state:                     present
      name:                      "LoD Inventory"
      description:               "Inventory for virtual lab environment"
      organization:              "NetApp LoD"
      <<: *input

  - name: Add LoD Inventory Source - From Project Root
    tower_inventory_source:
      state:                     present
      name:                      "Project Root Inventory"
      description:               "Inventory file sourced from root of pilot folder"
      inventory:                 "LoD Inventory"
      source:                    "scm"
      source_project:            "LoD Demo - Ansible Pilot"
      source_path:               "ansible_pilot/inventory"
      update_on_project_update:  True
      update_on_launch:          False
      overwrite:                 True
      <<: *input

  - name: Create Job Template for "Single SVM Create"
    tower_job_template:
      state:                     present
      name:                      "Single SVM Create"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/01_Single_SVM_Create.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Single SVM Create'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Management Interface Name"
          description:           "LIF to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_ip_interface_name"
        - question_name:         "Source Inventory?"
          description:           "Should the data be retreived from an Ansible Inventory?"
          required:              False
          type:                  "multiplechoice"
          choices:               "false\ntrue"
          variable:              "source_inventory"

      <<: *input

  - name: Create Job Template for "Single IP Interface Create"
    tower_job_template:
      state:                     present
      name:                      "Single IP Interface Create"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/02_Single_IP_Interface_Create.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Single IP Interface Create'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "IP Interface Name"
          description:           "LIF to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_ip_interface_name"
        - question_name:         "Source Inventory?"
          description:           "Should the data be retreived from an Ansible Inventory?"
          required:              False
          type:                  "multiplechoice"
          choices:               "false\ntrue"
          variable:              "source_inventory"
      <<: *input

  - name: Create Job Template for "Single Volume Create"
    tower_job_template:
      state:                     present
      name:                      "Single Volume Create"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/03_Single_Volume_Create.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Single Volume Create'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Volume Name"
          description:           "Volume to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_volume_name"
        - question_name:         "Source Inventory?"
          description:           "Should the data be retreived from an Ansible Inventory?"
          required:              False
          type:                  "multiplechoice"
          choices:               "false\ntrue"
          variable:              "source_inventory"
      <<: *input

  - name: Create Job Template for "Single Qtree Create"
    tower_job_template:
      state:                     present
      name:                      "Single Qtree Create"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/04_Single_Qtree_Create.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Single Qtree Create'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Volume Name"
          description:           "Volume to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_volume_name"
        - question_name:         "Qtree Name"
          description:           "Qtree to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_qtree_name"
        - question_name:         "Source Inventory?"
          description:           "Should the data be retreived from an Ansible Inventory?"
          required:              False
          type:                  "multiplechoice"
          choices:               "false\ntrue"
          variable:              "source_inventory"
      <<: *input

  - name: Create Job Template for "Single Quota Create"
    tower_job_template:
      state:                     present
      name:                      "Single Quota Create"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/05_Single_Quota_Create.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Single Quota Create'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Volume Name"
          description:           "Volume to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_volume_name"
# FIXME - Requires additional input. Type is obviously not enough
        - question_name:         "Quota Type"
          description:           "Quota to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_quota_type"
        - question_name:         "Source Inventory?"
          description:           "Should the data be retreived from an Ansible Inventory?"
          required:              False
          type:                  "multiplechoice"
          choices:               "false\ntrue"
          variable:              "source_inventory"
      <<: *input

  - name: Create Job Template for "Full SVM Create"
    tower_job_template:
      state:                     present
      name:                      "Full SVM Create"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/10_Full_SVM_Template_Create.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Full SVM Create'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Source Inventory?"
          description:           "Should the data be retreived from an Ansible Inventory?"
          required:              False
          type:                  "multiplechoice"
          choices:               "false\ntrue"
          variable:              "source_inventory"
      <<: *input

  - name: Create Job Template for "Full SVM Read Status"
    tower_job_template:
      state:                     present
      name:                      "Full SVM Read Status"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/80_Full_SVM_Read_Status.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Full SVM Read Status'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
        - question_name:         "Volume Name"
          description:           "Volume to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_volume_name"
        - question_name:         "Qtree Name"
          description:           "Qtree to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_qtree_name"
        - question_name:         "Source Inventory?"
          description:           "Should the data be retreived from an Ansible Inventory?"
          required:              False
          type:                  "multiplechoice"
          choices:               "false\ntrue"
          variable:              "source_inventory"
      <<: *input

  - name: Create Job Template for "Full SVM Delete"
    tower_job_template:
      state:                     present
      name:                      "Full SVM Delete"
      job_type:                  "run"
      inventory:                 "LoD Inventory"
      project:                   "LoD Demo - Ansible Pilot"
      playbook:                  "ansible_pilot/playbooks/99_Full_SVM_Delete.yml"
      credential:                "ONTAP Default Credentials"
      ask_variables_on_launch:   "yes"
      survey_enabled:            "yes"
      survey_spec:
        name:                    "Default Survey for 'Full SVM Delete'"
        description:             ""
        spec:
        - question_name:         "Cluster Name"
          description:           "ONTAP Cluster to act on"
          required:              True
          type:                  "text"
          variable:              "ontap_cluster_name"
        - question_name:         "SVM Name"
          description:           "SVM to act on"
          required:              False
          type:                  "text"
          variable:              "ontap_svm_name"
      <<: *input