---
- hosts: "{{ cluster_name }}"
  gather_facts: false

  tasks:
  - name: Include svm role
    include_role:
      name: ontap_svm

    tags: always
  - name: Print name after role
    ansible.builtin.debug:
      msg: "hoho : {{ name }}"
    tags: always
