---
- hosts:        "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:    "create"
    source_inventory:            true
    ontap_svm_name:              "pri_svm_01"
  
  tasks:
  - name: Create SVMs from Inventory
    include_role:
      name:                      ontap_svm

  - name: Get volumes to be created
    ansible.builtin.set_fact:
      task_vol_list:             "{{ item.volumes }}"
    loop:
      "{{ hostvars[ontap_cluster_name].svms | list }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - item.name == ontap_svm_name

  - name: Create SVM volumes
    include_role:
      name:                      ontap_volume
    vars:
      __ontap_volume_input__:    "{{ item }}"
      ontap_volume_name:         "{{ item.name }}"
    loop:
      "{{ task_vol_list | list }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Get Qtrees to be created
    ansible.builtin.set_fact:
      task_qt_list:              "{{ task_qt_list |
                                    default ([]) + item.1.qtrees
                                    }}"
    loop:
      "{{ q('subelements', hostvars[ontap_cluster_name].svms, 'volumes') }}"
    loop_control:
      label: "{{ item.0.name }}:{{ item.1.name }}"
    when:
      - item.0.name == ontap_svm_name

  - name: Create SVM qtrees from Inventory
    include_role:
      name:                      ontap_qtree
    vars:
      __ontap_qtree_input__:    "{{ item }}"
      ontap_volume_name:        "{{ item.volume.name }}"
      ontap_qtree_name:         "{{ item.name }}"
    loop:
      "{{ task_qt_list | list }}"
    loop_control:
      label: "{{ item.name }}"
