---
- hosts: "{{ cluster_name }}"
  gather_facts: false
  #vars_files:
  #  - ./roles/ontap_svm/vars/template_mirko.yml
  tasks:

  - name: register flags
    set_fact:
      svm_action: "delete"
    tags:
      - never
      - delete
  - name: register flags
    set_fact:
      svm_action: "create"
    tags:
      - create

  - name: create svm by hostvars
    block:
    - name: Include svm role by hostvars
      include_role:
        name: ontap_svm
      vars:
        ontap_svm_name: "{{ svm_name1 }}"
        __action__: "{{ svm_action | default('create')}}"
    - name: Register SVM
      ansible.builtin.set_fact:
        ontap_svm_registry: "{{ ontap_svm_registry|default({}) | combine( {ontap_svm_obj.name: ontap_svm_obj} ) }}"
    tags: by_hostvars
  - name: create svm by template
    block:
    - name: Include svm role by template
      include_role:
        name: ontap_svm
        vars_from: "{{ svm_template | default('main') }}"
      vars:
        __input__: "{{obj_svm}}"
        __action__: "{{ svm_action | default('create')}}"
        __ip_interface_template__: "{{ ip_interface_template }}"
    - name: Register SVM
      ansible.builtin.set_fact:
        ontap_svm_registry: "{{ ontap_svm_registry|default({}) | combine( {ontap_svm_obj.name: ontap_svm_obj} ) }}"
    tags: by_template

  - name: Print processed SVMs
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ontap_svm_registry | list}}"
    tags:
      - by_template
      - by_hostvars
