---
- hosts:        "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:    "create"
    source_inventory:            true
    ontap_svm_name:              "pri_svm_01"
  
  tasks:
  - name: Create SVMs from Inventory
    include_role:
      name:                      ontap_svm

  - name: Create SVM volumes from Inventory
    include_role:
      name:                      ontap_volume
    vars:
      __ontap_volume_input__:    "{{ item.value }}"
      ontap_volume_name:         "{{ item.value.name }}"
    loop:
      "{{ hostvars[ontap_cluster_name].svms[ontap_svm_name].volumes | list }}"
    loop_control:
      label: "{{ item.key }}"

  - name: Create SVM qtrees from Inventory
    include_role:
      name:                      ontap_qtree
    vars:
      __ontap_qtree_input__:    "{{ item.value }}"
      ontap_qtree_name:         "{{ item.value.name }}"
    loop:
      "{{ hostvars[ontap_cluster_name].svms[ontap_svm_name].volumes | list | subelements('qtrees') }}"
    loop_control:
      label: "{{ item.key }}"