---
# tasks file for ontap_qtree
##############################################################
### Run Pre-steps
##############################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must pass the 'ontap_qtree_name', 'ontap_volume_name' and 'ontap_svm_name'"
      - "or the '__ontap_qtree_input__' variable"
  when:
    - ((ontap_qtree_name is undefined or
      ontap_volume_name is undefined or
      ontap_svm_name is undefined) and
      __ontap_qtree_input__ is undefined)
  tags:
    - always

- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true
  tags:
    - always

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        ontap_svm_object: "{{ item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name == ontap_svm_name
    - name: Find Volume
      ansible.builtin.set_fact:
        ontap_volume_object: "{{ item }}"
      loop:
        "{{ ontap_svm_object.volumes | list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name == ontap_volume_name
    - name: Find Qtree
      ansible.builtin.set_fact:
        ontap_qtree_object: "{{ item }}"
      loop:
        "{{ ontap_volume_object.qtrees | list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name == ontap_qtree_name
  when:
    - source_inventory is defined
    - source_inventory == true
# FIXME - Additioanl condition required to check, if SVM has been found in inventory

- name: Source Template Information
  block:
    - name: Merge Defaults/Vars with Input
      ansible.builtin.set_fact:
        ontap_volume_object: "{{ ontap_qtree_object | combine(__ontap_qtree_input__, recursive=True) }}"
  when:
    - __ontap_qtree_input__ is defined



##############################################################
### Initiate Action
##############################################################

- name: Read Qtree Information into 'ontap_qtree_object'
  include_tasks:      ontap_qtree_info.yml
  vars:
    ontap_login:
      <<: *ontap_login
  when:
    - ontap_ansiblerole_action == "info"

- name: Create Qtree
  include_tasks:      ontap_qtree_create.yml
  vars:
    ontap_login:
      <<: *ontap_login
  when:
    - ontap_ansiblerole_action == "create"

- name: Delete Qtree
  include_tasks:      ontap_qtree_delete.yml
  vars:
    ontap_login:
      <<: *ontap_login
  when:
    - ontap_ansiblerole_action == "delete"