---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Delete Qtree
  na_ontap_qtree:
    state:                        absent
    name:                         "{{ ontap_qtree_name }}"
    flexvol_name:                 "{{ ontap_volume_name }}"
    vserver:                      "{{ ontap_svm_name }}"
    <<: *ontap_login
