---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Get Qtree Info
  na_ontap_rest_info:
    gather_subset:
      - storage/qtree
    parameters:
      svm.name:                   "{{ ontap_qtree_object.svm.name }}"
      volume.name:                "{{ ontap_qtree_object.volume.name }}"
      name:                       "{{ ontap_qtree_object.name }}"
    fields:
# FIXME - List of required fields has to be added for to improve overall efficiency
      - '**'
    <<: *ontap_login
  register: __ontap_qtree_input__

- name: Set ontap_qtree_object
  ansible.builtin.set_fact:
    ontap_qtree_object: "{{ __ontap_qtree_input__.ontap_info['storage/qtrees'].records[0] }}"
  when:
  - __ontap_qtree_input__.ontap_info['storage/qtrees'].num_records == 1

- name: Debug ontap_qtree_object
  ansible.builtin.debug:
    msg: "{{ ontap_qtree_object }}"