---
# tasks file for ontap_svm
################################################################################
#
# Variables accepted by this role:
# -------------------------------
#
# Mandatory:
# __ontap_ansiblerole_action__:        create, delete, info
# __ontap_svm_input__:                 Input object with additional optional
#                                      parameters to action on
#                                      (according to SVM data model)
#                    Mandatory childs: .name - SVM name
#
# Optional:
# __ontap_ip_interface_name__:
#                                      Management interface for "create" to
#                                      allow configuration of network services
# __ontap_source_inventory__:          Source object input from Ansible
#                                      inventory and host/group vars
# 
################################################################################



################################################################################
### Run role input validation
################################################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must provide '__ontap_svm_input__' including child(s):
        .name"
      - "and '__ontap_ansiblerole_action__'"
      - "> __ontap_svm_input__.name:     {{ __ontap_svm_input__.name | default ('') }}"
      - "> __ontap_ansiblerole_action__: {{ __ontap_ansiblerole_action__ | default ('') }}"
  when:
    - __ontap_svm_input__.name | default('') == ""
    - (__ontap_ansiblerole_action__ | default('')) not in ["create", "delete", "info"]
  tags:
    - always



################################################################################
### Source input parameters into object
################################################################################

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        __ontap_svm_object__: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == __ontap_svm_input__.name
  when:
    - __ontap_source_inventory__ is defined
    - __ontap_source_inventory__ | bool

- name: Merge Defaults/Vars with Input
  ansible.builtin.set_fact:
    __ontap_svm_object__: "{{ __ontap_svm_object__ | default({}) | combine(__ontap_svm_input__, recursive=True) }}"

- name: Verify Data Sourcing
  fail:
    msg:
      - "Mandatory data could not be sourced:"
      - "> __ontap_svm_object__.name --> {{ __ontap_svm_object__.name }}"
  when:
    - __ontap_svm_object__.name | default('') == ""
  tags:
    - always



################################################################################
### Initiate role action
################################################################################

- name: Read SVM Information into 'ontap_volume_object'
  include_tasks:      ontap_svm_info.yml
  when:
    - __ontap_ansiblerole_action__ == "info"

- name: Create SVM
  include_tasks:      ontap_svm_create.yml
  when:
    - __ontap_ansiblerole_action__ == "create"

- name: Delete SVM
  include_tasks:      ontap_svm_delete.yml
  when:
    - __ontap_ansiblerole_action__ == "delete"