---
# tasks file for ontap_svm
###############################################################
### Run Pre-steps
##############################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must either pass 'ontap_svm_name' 
        or pass  '__ontap_svm_input__' including child(s): .name"
      - "- ontap_ip_interface_name is an optional input"
      - "> ontap_svm_name:           {{ ontap_svm_name | default('') }}"
      - "> __ontap_svm_input__.name: {{ __ontap_svm_input__.name | default ('') }}"
  when:
    - ((ontap_svm_name | default('') == "")
        and
       (__ontap_svm_input__.name | default('') == "")
      )
  tags:
    - always

- name: Validate Action
  fail:
    msg:
      - "You must pass the '__ontap_ansiblerole_action__' variable"
  when:
    - __ontap_ansiblerole_action__ is undefined
  tags:
    - always

- name: Add mandatory Input to SVM object
  ansible.builtin.set_fact:
    ontap_svm_object:
      name:                  "{{ ontap_svm_name }}"
  when:
    - not (ontap_svm_name          | default('') == "") or
      not (ontap_ip_interface_name | default('') == "")

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        ontap_svm_object: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == ontap_svm_object.name
  when:
    - __source_inventory__ is defined
    - __source_inventory__

- name: Merge Defaults/Vars with Input
  ansible.builtin.set_fact:
    ontap_svm_object: "{{ ontap_svm_object | combine(__ontap_svm_input__, recursive=True) }}"
  when:
    - __ontap_svm_input__ is defined

- name: Verify Data Sourcing
  fail:
    msg:
      - "Mandatory data could not be sourced:"
      - "> ontap_svm_object.name --> {{ ontap_svm_object.name }}"
  when:
    - ontap_svm_object.name | default('') == ""
  tags:
    - always



##############################################################
### Initiate Action
##############################################################

- name: Read SVM Information into 'ontap_volume_object'
  include_tasks:      ontap_svm_info.yml
  when:
    - __ontap_ansiblerole_action__ == "info"

- name: Create SVM
  include_tasks:      ontap_svm_create.yml
  when:
    - __ontap_ansiblerole_action__ == "create"

- name: Delete SVM
  include_tasks:      ontap_svm_delete.yml
  when:
    - __ontap_ansiblerole_action__ == "delete"