---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Get SVM Info
  na_ontap_rest_info:
    gather_subset:
      - svm/svms
    parameters:
      name:                       "{{ __ontap_svm_object__.name }}"
    fields:
# FIXME - List of required fields has to be added for to improve overall efficiency
      - '**'
    <<: *ontap_login
  register: __ontap_svm_return__

- name: Set __ontap_svm_return_clean__
  ansible.builtin.set_fact:
    __ontap_svm_return_clean__: "{{ __ontap_svm_return__.ontap_info['svm/svms'].records[0] }}"
  when:
  - __ontap_svm_return__.ontap_info['svm/svms'].num_records == 1

- name: Debug __ontap_svm_return_clean__
  ansible.builtin.debug:
    msg: "{{ __ontap_svm_return_clean__ }}"