---
# tasks file for ontap_ip_interface
################################################################################
#
# Variables accepted by this role:
# -------------------------------
#
# Mandatory:
# __ontap_ansiblerole_action__:        create, delete, info
# __ontap_ip_interface_input__:        Input  object with additional optional
#                                      parameters to action on
#                                      (according to SVM data model)
#                    Mandatory childs: .name     - LIF name
#                                      .svm.name - Owning SVM
#
# Optional:
# __ontap_source_inventory__:          Source object input from Ansible
#                                      inventory and host/group vars
# 
################################################################################



################################################################################
### Run role input validation
################################################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must provide '__ontap_ip_interface_input__' including child(s):
        .name, .svm.name"
      - "and '__ontap_ansiblerole_action__'"
      - "> __ontap_ip_interface_input__.svm.name: {{ __ontap_ip_interface_input__.svm.name | default ('') }}"
      - "> __ontap_ip_interface_input__.name:     {{ __ontap_ip_interface_input__.name | default ('') }}"
      - "> __ontap_ansiblerole_action__:          {{ __ontap_ansiblerole_action__ | default ('') }}"
  when:
    - (__ontap_ip_interface_input__.svm.name | default('') == "" or
       __ontap_ip_interface_input__.name     | default('') == ""
       )
    - (__ontap_ansiblerole_action__ | default('')) not in ["create", "delete", "info"]
  tags:
    - always



################################################################################
### Source input parameters into object
################################################################################

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        __ontap_svm_object__: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == __ontap_ip_interface_input__.svm.name
    - name: Find IP Interface
      ansible.builtin.set_fact:
        __ontap_ip_interface_object__: "{{ ip_interface_item }}"
      loop:
        "{{ __ontap_svm_object__.ip_interfaces | list }}"
      loop_control:
        label:    "{{ ip_interface_item.name }}"
        loop_var: ip_interface_item
      when:
        - ip_interface_item.name == __ontap_ip_interface_input__.name
  when:
    - __ontap_source_inventory__ is defined
    - __ontap_source_inventory__

- name: Merge Defaults/Vars with Input
  ansible.builtin.set_fact:
    __ontap_ip_interface_object__: "{{ (__ontap_ip_interface_object__ | default({})) | combine(__ontap_ip_interface_input__, recursive=True) }}"
  when:
    - __ontap_ip_interface_input__ is defined

- name: Verify Data Sourcing
  fail:
    msg:
      - "Mandatory data could not be sourced:"
      - "> __ontap_ip_interface_object__.svm.name --> {{ __ontap_ip_interface_object__.svm.name }}"
      - "> __ontap_ip_interface_object__.name     --> {{ __ontap_ip_interface_object__.name }}"
  when:
    - __ontap_ip_interface_object__.svm.name | default('') == "" or
      __ontap_ip_interface_object__.name     | default('') == ""
  tags:
    - always



################################################################################
### Initiate role action
################################################################################

- name: Read LIF Information into 'ontap_ip_interface_object'
  include_tasks:      ontap_ip_interface_info.yml
  when:
    - __ontap_ansiblerole_action__ == "info"

- name: Create LIF
  include_tasks:      ontap_ip_interface_create.yml
  when:
    - __ontap_ansiblerole_action__ == "create"

- name: Delete LIF
  include_tasks:      ontap_ip_interface_delete.yml
  when:
    - __ontap_ansiblerole_action__ == "delete"