---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Create IP Interface
  na_ontap_interface:
    state:                        present
    interface_name:               "{{ __ontap_ip_interface_object__.name }}"
    vserver:                      "{{ __ontap_ip_interface_object__.svm.name }}"
    address:                      "{{ __ontap_ip_interface_object__.ip.address              | default(omit) }}"
    netmask:                      "{{ __ontap_ip_interface_object__.ip.netmask              | default(omit) }}"
    service_policy:               "{{ __ontap_ip_interface_object__.service_policy.name     | default(omit) }}"
    home_node:                    "{{ __ontap_ip_interface_object__.location.home_node.name | default(omit) }}"
    home_port:                    "{{ __ontap_ip_interface_object__.location.home_port.name | default(omit) }}"
# FIXME - This one is ugly, but "role" must be provided as long as we have to use ZAPI here
    role:                         "data"
    <<: *ontap_login