---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Get LIF Info
  na_ontap_rest_info:
    gather_subset:
      - network/ip/interfaces
    parameters:
      svm.name:                   "{{ __ontap_ip_interface_object__.svm.name }}"
      name:                       "{{ __ontap_ip_interface_object__.name }}"
    fields:
# FIXME - List of required fields has to be added for to improve overall efficiency
      - '**'
  register: __ontap_ip_interface_return__

- name: Set __ontap_ip_interface_return_clean__
  ansible.builtin.set_fact:
    __ontap_ip_interface_return_clean__: "{{ __ontap_ip_interface_return__.ontap_info['network/ip/interfaces'].records[0] }}"
  when:
  - __ontap_ip_interface_return__.ontap_info['network/ip/interfaces'].num_records == 1

- name: Debug __ontap_ip_interface_return_clean__
  ansible.builtin.debug:
    msg: "{{ __ontap_ip_interface_return_clean__ }}"