---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Delete IP Interface
  na_ontap_interface:
    state:                        absent
    interface_name:               "{{ ontap_ip_interface_object.name }}"
    vserver:                      "{{ ontap_ip_interface_object.svm.name }}"
    <<: *ontap_login