---
# tasks file for ontap_volume
################################################################################
#
# Variables accepted by this role:
# -------------------------------
#
# Mandatory:
# __ontap_ansiblerole_action__:        create, delete, info
# __ontap_volume_input__:              Input object with additional optional
#                                      parameters to action on
#                                      (according to SVM data model)
#                    Mandatory childs: .name     - Volume name
#                                      .svm.name - Owning SVM
#
# Optional:
# __ontap_source_inventory__:          Source object input from Ansible
#                                      inventory and host/group vars
# 
################################################################################



################################################################################
### Run role input validation
################################################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must provide '__ontap_volume_input__' including child(s):
        .name, .svm.name"
      - "and '__ontap_ansiblerole_action__'"
      - "> __ontap_volume_input__.svm.name: {{ __ontap_volume_input__.svm.name | default ('') }}"
      - "> __ontap_volume_input__.name:     {{ __ontap_volume_input__.name | default ('') }}"
      - "> __ontap_ansiblerole_action__:    {{ __ontap_ansiblerole_action__ | default ('') }}"
  when:
    - (__ontap_volume_input__.svm.name | default('') == "" or
       __ontap_volume_input__.name     | default('') == ""
       )
    - "> __ontap_volume_input__.name: {{ __ontap_volume_input__.name | default ('') }}"
  tags:
    - always



################################################################################
### Source input parameters into object
################################################################################

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        ___ontap_svm_object__: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == __ontap_volume_input__.svm.name
    - name: Find Volume
      ansible.builtin.set_fact:
        __ontap_volume_object__: "{{ volume_item }}"
      loop:
        "{{ ___ontap_svm_object__.volumes | list }}"
      loop_control:
        label:    "{{ volume_item.name }}"
        loop_var: volume_item
      when:
        - volume_item.name == __ontap_volume_input__.name
  when:
    - __ontap_source_inventory__ is defined
    - __ontap_source_inventory__ | bool

- name: Merge Defaults/Vars with Input
  ansible.builtin.set_fact:
    __ontap_volume_object__: "{{ __ontap_volume_object__ | default({}) | combine(__ontap_volume_input__, recursive=True) }}"

- name: Verify Data Sourcing
  fail:
    msg:
      - "Mandatory data could not be sourced:"
      - "> __ontap_volume_object__.svm.name --> {{ ontap_volume_object.svm.name }}"
      - "> __ontap_volume_object__.name     --> {{ ontap_volume_object.name }}"
  when:
    - __ontap_volume_object__.svm.name | default('') == "" or
      __ontap_volume_object__.name     | default('') == ""
  tags:
    - always



################################################################################
### Initiate role action
################################################################################

- name: Read Volume Information into 'ontap_volume_object'
  include_tasks:      ontap_volume_info.yml
  when:
    - __ontap_ansiblerole_action__ == "info"

- name: Create Volume
  include_tasks:      ontap_volume_create.yml
  when:
    - __ontap_ansiblerole_action__ == "create"

- name: Delete Volume
  include_tasks:      ontap_volume_delete.yml
  when:
    - __ontap_ansiblerole_action__ == "delete"