---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Delete Volume
  na_ontap_volume:
    state:                        absent
    name:                         "{{ __ontap_volume_object__.name }}"
    vserver:                      "{{ __ontap_volume_object__.svm.name }}"
    <<: *ontap_login
