---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Get Volume Info
  na_ontap_rest_info:
    gather_subset:
      - storage/volumes
    parameters:
      svm.name:                   "{{ __ontap_volume_object__.svm.name }}"
      name:                       "{{ __ontap_volume_object__.name }}"
    fields:
# FIXME - List of required fields has to be added for to improve overall efficiency
      - '**'
    <<: *ontap_login
  register: __ontap_volume_return__

- name: Set ontap_volume_object
  ansible.builtin.set_fact:
    __ontap_volume_return_clean__: "{{ __ontap_volume_return__.ontap_info['storage/volumes'].records[0] }}"
  when:
  - __ontap_volume_return__.ontap_info['storage/volumes'].num_records == 1 

- name: Debug __ontap_volume_return_clean__
  ansible.builtin.debug:
    msg: "{{ __ontap_volume_return_clean__ }}"