---
- hosts:        "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:     "create"
  
  tasks:
  - name: Create SVM
    include_role:
      name:                       ../roles/ontap_svm
    vars:
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"