---
################################################################################
# Description:
# -----------
# - Reading information from live system
# - Retreives data based on input (ontap_svm_name, ontap_ip_interface_name,
#   ontap_volume_name and ontap_qtree_name)
# - Or taking full '__ontap_svm_input__' (including childs) or single object
#   inputs
# - Or sourcing SVM info from the inventory by taking 'ontap_svm_name' and
#   'source_inventory=true'
################################################################################
- hosts:                          "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:     "info"
  
  tasks:
  - name: Read SVM
    include_role:
      name:                       ../roles/ontap_svm
    vars:
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
      __source_inventory__:       "{{ source_inventory }}"

  - name: Get list of IP Interfaces to be read
    ansible.builtin.set_fact:
      task_lif_list:              "{{ ontap_svm_object.ip_interfaces }}"

  - name: Read SVM IP Interfaces
    include_role:
      name:                       ../roles/ontap_ip_interface
    vars:
      __ontap_ip_interface_input__:
                                  "{{ task_lif_item }}"
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
      __source_inventory__:       false
    loop:
      "{{ task_lif_list | list }}"
    loop_control:
      label:    "{{ task_lif_item.name }}"
      loop_var: task_lif_item

  - name: Get list of Volumes to be read
    ansible.builtin.set_fact:
      task_vol_list:              "{{ ontap_svm_object.volumes }}"

  - name: Read SVM Volumes
    include_role:
      name:                       ../roles/ontap_volume
    vars:
      __ontap_volume_input__:     "{{ task_vol_item }}"
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
      __source_inventory__:       false
    loop:
      "{{ task_vol_list | list }}"
    loop_control:
      label:    "{{ task_vol_item.name }}"
      loop_var: task_vol_item

  - name: Get Qtrees to be read
    ansible.builtin.set_fact:
      task_qt_list:               "{{ task_qt_list |
                                      default ([]) + task_qt_item.qtrees
                                      }}"
    loop:
      "{{ ontap_svm_object.volumes }}"
    loop_control:
      label:    "{{ task_qt_item.qtrees | default('no qtrees found')}}"
      loop_var: task_qt_item

  - name: Read SVM Qtrees
    include_role:
      name:                       ../roles/ontap_qtree
    vars:
      __ontap_qtree_input__:      "{{ task_qt_item }}"
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
      __source_inventory__:       false
    loop:
      "{{ task_qt_list | list }}"
    loop_control:
      label:    "{{ task_qt_item.name }}"
      loop_var: task_qt_item