---
################################################################################
# Description:
# -----------
# - Deleting an entire SVM with all child items (ip_interfaces, volumes,
#   qtrees, quotas...)
# - Taking 'ontap_svm_name' to discovery and delete all resources on the cluster
#
################################################################################
- hosts:                          "{{ ontap_cluster_name }}"
  gather_facts: false
  vars:
    ontap_ansiblerole_action:     "delete"
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never

  tasks:
  - name: Extract list of volumes to be created
    netapp.ontap.na_ontap_rest_info:
      gather_subset:
        - storage/volumes
      parameters:
        svm.name:                 "{{ ontap_svm_name }}"
      fields:
        - 'is_svm_root'
      <<: *ontap_login
    register: ontap_svm_volumes

  - name: Delete SVM volumes
    include_role:
      name:                       ../roles/ontap_volume
    vars:
      __ontap_volume_input__:     "{{ task_vol_item }}"
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"
    loop:
      "{{ ontap_svm_volumes.ontap_info['storage/volumes'].records | list }}"
    loop_control:
      label:    "{{ task_vol_item.name }}"
      loop_var: task_vol_item
    when:
      - not task_vol_item.is_svm_root

  - name: Delete SVM
    include_role:
      name:                       ../roles/ontap_svm
    vars:
      __ontap_ansiblerole_action__:
                                  "{{ ontap_ansiblerole_action }}"