---
# tasks file for ontap_volume
##############################################################
### Run Pre-steps
##############################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must either pass 'ontap_volume_name' and 'ontap_svm_name' 
        or '__ontap_volume_input__' including child(s): .name, .svm.name"
      - "> ontap_svm_name:                  {{ ontap_svm_name | default('') }}"
      - "> ontap_volume_name:               {{ ontap_volume_name | default('') }}"
      - "> __ontap_volume_input__.svm.name: {{ __ontap_volume_input__.svm.name | default ('') }}"
      - "> __ontap_volume_input__.name:     {{ __ontap_volume_input__.name | default ('') }}"
  when:
    - ((ontap_svm_name    | default('') == "" or
        ontap_volume_name | default('') == ""
        ) and
       (__ontap_volume_input__.svm.name | default('') == "" or
        __ontap_volume_input__.name     | default('') == ""
        ))
  tags:
    - always

- name: Validate Action
  fail:
    msg:
      - "You must pass the 'ontap_ansiblerole_action' variable"
  when:
    - ontap_ansiblerole_action is undefined
  tags:
    - always

- name: Add mandatory Input to Volume object
  ansible.builtin.set_fact:
    ontap_volume_object:
      svm:
        name:                "{{ ontap_svm_name }}"
      name:                  "{{ ontap_volume_name }}"
  when:
    - not (ontap_svm_name    | default('') == "") or
      not (ontap_volume_name | default('') == "")
      
- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        ontap_svm_object: "{{ svm_item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label:    "{{ svm_item.name }}"
        loop_var: svm_item
      when:
        - svm_item.name == ontap_svm_name
    - name: Find Volume
      ansible.builtin.set_fact:
        ontap_volume_object: "{{ volume_item }}"
      loop:
        "{{ ontap_svm_object.volumes | list }}"
      loop_control:
        label:    "{{ volume_item.name }}"
        loop_var: volume_item
      when:
        - volume_item.name == ontap_volume_name
  when:
    - source_inventory is defined
    - source_inventory == true

- name: Merge Defaults/Vars with Input
  ansible.builtin.set_fact:
    ontap_volume_object: "{{ ontap_volume_object | combine(__ontap_volume_input__, recursive=True) }}"
  when:
    - __ontap_volume_input__ is defined

- name: Verify Data Sourcing
  fail:
    msg:
      - "Mandatory data could not be sourced:"
      - "> ontap_volume_object.svm.name --> {{ ontap_volume_object.svm.name }}"
      - "> ontap_volume_object.name     --> {{ ontap_volume_object.name }}"
  when:
    - ontap_volume_object.svm.name | default('') == "" or
      ontap_volume_object.name     | default('') == ""
  tags:
    - always

##############################################################
### Initiate Action
##############################################################

- name: Read Volume Information into 'ontap_volume_object'
  include_tasks:      ontap_volume_info.yml
  when:
    - ontap_ansiblerole_action == "info"

- name: Create Volume
  include_tasks:      ontap_volume_create.yml
  when:
    - ontap_ansiblerole_action == "create"

- name: Delete Volume
  include_tasks:      ontap_volume_delete.yml
  when:
    - ontap_ansiblerole_action == "delete"