---
# tasks file for ontap_volume
##############################################################
### Run Pre-steps
##############################################################

- name: Validate Mandatory Input
  fail:
    msg:
      - "You must pass the 'ontap_volume_name' and 'ontap_svm_name'"
      - "or the '__ontap_volume_input__' variable"
  when:
    - ((ontap_volume_name is undefined or
      ontap_svm_name is undefined) and
      __ontap_volume_input__ is undefined)
  tags:
    - always

- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true
  tags:
    - always

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        ontap_svm_object: "{{ item }}"
      loop:
        "{{ svms | list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name == ontap_svm_name
    - name: Find Volume
      ansible.builtin.set_fact:
        ontap_volume_object: "{{ item }}"
      loop:
        "{{ ontap_svm_object.volumes | list}}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name == ontap_volume_name
  tags:
    - source_inventory
# FIXME - Additioanl condition required to check, if SVM has been found in inventory

- name: Source Template Information
  block:
    - name: Merge Defaults/Vars with Volume Input
      ansible.builtin.set_fact:
        ontap_volume_object: "{{ ontap_volume_object | combine(__ontap_volume_input__, recursive=True) }}"
  when:
    - __ontap_volume_input__ is defined



##############################################################
### Initiate Action
##############################################################

- include:           ontap_volume_infoyml
  when:
    - ontap_ansiblerole_action == "info"

- include:           ontap_volume_create.yml
  when:
    - ontap_ansiblerole_action == "create"

- include:           ontap_volume_delete.yml
  when:
    - ontap_ansiblerole_action == "delete"