---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Create Volume (FlexVol)
  na_ontap_volume:
    state:                        present
    name:                         "{{ ontap_volume_name }}"
    vserver:                      "{{ ontap_svm_name }}"
    comment:                      "{{ ontap_volume_object.comment                        | default(omit) }}"
    aggregate_name:               "{{ ontap_volume_object.aggregates[0].name             | default(omit) }}"
    size:                         "{{ ontap_volume_object.size                           | default(omit) }}"
    size_unit:                    "b"
    space_guarantee:              "{{ ontap_volume_object.guarantee.type                 | default(omit) }}"
    export_policy:                "{{ ontap_volume_object.nas.export_policy.name         | default(omit) }}"
    percent_snapshot_space:       "{{ ontap_volume_object.space.snapshot.reserve_percent | default(omit) }}"
    volume_security_style:        "{{ ontap_volume_object.nas.security_style             | default(omit) }}"
    type:                         "{{ ontap_volume_object.type                           | default(omit) }}"
    qos_policy_group: 
# FIXME - Parameter needs to be investigated
    wait_for_completion:          True
    <<: *ontap_login
  when:
    - ( ontap_volume_object.aggregates | length ) == 1

# FIXME - Not developed yet
- name: Create Volume (FlexGroup)
  na_ontap_volume:
    state:                        present
    name:                         "{{ ontap_volume_name }}"
    vserver:                      "{{ ontap_svm_name }}"
    <<: *ontap_login
  when:
    - ( ontap_volume_object.aggregates | length ) > 1
    - 0 == 1

- name: Mount RW Volume
  na_ontap_volume:
    state:                        present
    name:                         "{{ ontap_volume_name }}"
    vserver:                      "{{ ontap_svm_name }}"
    junction_path:                "{{ ontap_volume_object.nas.path                       | default(omit) }}"
    <<: *ontap_login
  when:
    - ontap_volume_object.type is undefined or ontap_volume_object.type == "rw"
