---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Create Volume (FlexVol)
  na_ontap_rest_info:
    gather_subset:
    - storage/volumes
    parameters:
      name:                       "{{ ontap_volume_name }}"
      svm.name:                   "{{ ontap_svm_name }}"
    fields:
    - '*'
    <<: *ontap_login
  register: __ontap_volume_input__

- name: Set ontap_volume_object
  ansible.builtin.set_fact:
    ontap_volume_object: "{{ __ontap_volume_input__.ontap_info['storage/volumes'].records[0] }}"
  when:
  - __ontap_volume_input__.ontap_info['storage/volumes'].num_records == 1

- name: Debug ontap_volume_object
  ansible.builtin.debug:
    msg: "{{ ontap_volume_object }}"