---
- name: Delete SVM
  na_ontap_svm:
    state:                        absent
    name:                         "{{ ontap_svm_name }}"
    <<: *ontap_login
  tags:
    - never
    - delete_all
    - delete_ontap_svm
