---
- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  no_log: true

- name: Get SVM Info
  na_ontap_rest_info:
    gather_subset:
    - svm/svms
    parameters:
      name:                       "{{ ontap_svm_name }}"
    fields:
    - '*'
    <<: *ontap_login
  register: __ontap_svm_input__

- name: Set __ontap_svm_input__
  ansible.builtin.set_fact:
    ontap_svm_object: "{{ __ontap_svm_input__.ontap_info['storage/volumes'].records[0] }}"
  when:
  - __ontap_svm_input__.ontap_info['svm/svms'].num_records == 1

- name: Debug ontap_svm_object
  ansible.builtin.debug:
    msg: "{{ ontap_svm_object }}"